"""Initial migration

Revision ID: 8062eeb65a44
Revises: 
Create Date: 2023-12-15 23:18:54.669348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8062eeb65a44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
                    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
                    sa.Column('age', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
                    sa.Column('country', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
                    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
                    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                              nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('email', name='user_email_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('phonebook',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                              nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='phonebook_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='phonebook_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
